[platformio]
src_dir = firmware

[env:servo-home-test]
platform = espressif32@7.0.0
board = m5stack-cores3
framework = arduino

board_build.f_flash = 80000000L
board_build.partitions = default_16MB.csv

build_unflags =
    -std=gnu++11

build_flags =
    -O2
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
    -DUART_SCLK_DEFAULT=UART_SCLK_APB
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    m5stack/M5Unified@0.2.15
    m5stack/StackChan-BSP@1.1.0
    https://github.com/meganetaaan/m5stack-avatar.git

lib_ldf_mode = deep
